# -*- coding: utf-8 -*-
"""ömer faruk and zeynep project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NXs38ti6EFsX5ZOqto-huVJXf8AFlSbt
"""

import re

example1 = "/content/story.txt"
file1 = open(example1, "r")

file1

FileContent = file1.read()
print(FileContent)

ali = FileContent

# Python code that converts string to list
def Convert(string):
    awesome_list = list(string.split("\n"))
    return awesome_list
  
fatma = Convert(ali)

print(fatma)

ahmet = re.findall(r'"([^"]*)"', ali)
ahmet

regexp = re.compile("said(.*)$")
list_speakers = []
for i in range(len(fatma)):
  if '" said' in fatma[i]:
    k = fatma[i]
    plk = regexp.search(k).group(1)
    plk_2 = plk.replace(".", "")
    list_speakers.append(plk_2)
list_speakers

kl = []
for i in fatma:
  l = re.findall(r'\*.*?\*', i)

  kl.append(l)
kl[0] = "Little Red Riding Hood"
kl[-1] = "THE END"
kl

a = 0
p = 0
for i in kl:
  if i == []:
    print("")
    speakers = list_speakers[a]
    speakers_new = speakers.replace("'", "")
    speakers_new = speakers_new.replace(" the", "The") 
    print(speakers_new,":")
    print("-",ahmet[a])
    a = a + 1
  else:
    print("")
    j = fatma[p]
    print(j)
  p = p + 1